apiVersion: v1
kind: Service
metadata:
  name: tmwso2portal
  namespace: emsit
spec:
  selector:
    app: tmwso2portal
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portaltmwso2
  namespace: emsit
  labels:
    app: portaltmwso2
    tier: frontend
spec:
  selector:
    matchLabels:
      app: tmwso2portal
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: tmwso2portal
        tier: frontend
    spec:
      containers:
      - name: portaltmwso2
        image: harbor.dev.kubix.tm.com.my/wso2sit/tmwso2portal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "128Mi"
            cpu: "1000m"
          limits:
            memory: "256Mi"
            cpu: "2000m"
        env:
        - name: DB_USER
          value: "wso_app"
        - name: DB_PASSWORD
          value: "Pswd2019"
        - name: DB_NAME
          value: "wso"
        - name: DB_HOST
          value: "172.20.196.182"